### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by Veetaha** [TedDriggs/from_variants#5]
Hi, that's a great crate and exactly what I need, but it seems to have been abandoned for so long :d
@TedDriggs, will you be able accept any PRs to this repo and publish new crate versions to `crates.io`?

**Comment by TedDriggs** [comment]
I'm happy to review PRs, though I'm curious what changes you have in mind for the library.

**Comment by Veetaha** [comment]
The crucial change is at least moving to `edition = 2018` and updating all the dependencies (stale dependencies cause duplicates in my dependency tree which in turn adds up to compile times and general friction (I use [`cargo-deny`](https://github.com/EmbarkStudios/cargo-deny) to track this)).

**Comment by TedDriggs** [comment]
That sounds great to me, and happy to review. One thing I'm unclear on - how does the code generated by proc-macro crates interact with editions? Does this crate have to emit 2015-edition code to avoid breaking backwards compatibility?

**Comment by Veetaha** [comment]
Nope, `edition = 2018` is just a nice to have, it should actually be very easy to migrate to it, anyway the world will just be a better place if this crate uses the last Rust edition :D

**Comment by Veetaha** [comment]
Okay, thanks for quick feedback, I'll try to come up with PRs soon if no-one gets ahead, nice to hear the project is alive!

**Comment by TedDriggs** [comment]
Changes are live as v0.5.0, and I'm happy to review future PRs as-needed. Thanks for submitting those updates!
