### ISSUE TITLE
Add #![no_std] attribute

### ISSUE THREAD

**Issue by joboet** [TedDriggs/from_variants#7]
Building for no_std targets currently fails as the crate is missing a `#![no_std]` attribute.

**Comment by TedDriggs** [comment]
Oops, sorry about that. Trying that out now.

I'm still pretty confused on how proc-macros and `no_std` interact, so I may need to ask you to grab a branch via `Cargo.toml` and see if this works that way.

**Comment by TedDriggs** [comment]
And I just fat-fingered the close button; please ignore that closure.

**Comment by TedDriggs** [comment]
Alright, this is now in `master`. I've tested that it builds on a crate with `std`; can you let me know if it works on your `no_std` target? If it does I'll publish the update.

**Comment by joboet** [comment]
Indeed, it does build now. Thanks!

**Comment by TedDriggs** [comment]
0.6.0 is going out as soon as CI completes, so you'll be able to remove your repo dependency in ~5 minutes.
